# Generated by Django 4.2.2 on 2023-11-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_add_parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_name', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('parents_address', models.TextField()),
                ('parents_gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='admin_add_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_address', models.TextField()),
                ('student_course', models.CharField(max_length=50)),
                ('student_DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='admin_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=50)),
                ('admin_login_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='admin_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_profile_name', models.CharField(max_length=200)),
                ('admin_profile_address', models.TimeField()),
                ('admin_profile_gender', models.CharField(max_length=20)),
                ('admin_profile_M_number', models.CharField(max_length=20)),
                ('admin_profile_DOB', models.DateField()),
                ('admin_profile_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='admin_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_first_name', models.CharField(max_length=100)),
                ('admin_last_name', models.CharField(max_length=100)),
                ('admin_email', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=50)),
            ],
        ),
    ]
