# Generated by Django 4.2.2 on 2023-11-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_admin_add_course_admin_add_faculty_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin_add_course',
            new_name='add_course',
        ),
        migrations.RenameModel(
            old_name='Admin_add_faculty',
            new_name='add_faculty',
        ),
        migrations.RenameModel(
            old_name='admin_add_parent',
            new_name='add_parent',
        ),
        migrations.RenameModel(
            old_name='admin_add_student',
            new_name='add_student',
        ),
        migrations.RenameModel(
            old_name='Admin_event_activity_notice',
            new_name='event_activity_notice',
        ),
        migrations.RenameModel(
            old_name='Admin_exam_timetable',
            new_name='exam_timetable',
        ),
        migrations.RenameModel(
            old_name='admin_login',
            new_name='login',
        ),
        migrations.RenameModel(
            old_name='Admin_Notice',
            new_name='Notice',
        ),
        migrations.RenameModel(
            old_name='admin_profile',
            new_name='profile',
        ),
        migrations.RenameModel(
            old_name='admin_register',
            new_name='register',
        ),
        migrations.RenameModel(
            old_name='Admin_time_table',
            new_name='time_table',
        ),
    ]
