# Generated by Django 4.2.2 on 2023-11-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_admin_add_course_add_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_login_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
