# Generated by Django 4.2.2 on 2023-11-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.CharField(max_length=100)),
                ('student_password', models.CharField(max_length=50)),
                ('student_login_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_address', models.TextField()),
                ('student_email', models.CharField(max_length=50)),
                ('student_course', models.CharField(max_length=20)),
                ('student_DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_email', models.CharField(max_length=100)),
                ('student_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student_reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_std', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('reporting', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_upload_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_std', models.CharField(max_length=20)),
                ('student_assignment', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_upload_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_std', models.CharField(max_length=20)),
                ('student_projects', models.FilePathField()),
            ],
        ),
    ]
