# Generated by Django 4.2.2 on 2023-11-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_login',
            new_name='login',
        ),
        migrations.RenameModel(
            old_name='Student_profile',
            new_name='profile',
        ),
        migrations.RenameModel(
            old_name='Student_register',
            new_name='register',
        ),
        migrations.RenameModel(
            old_name='Student_reporting',
            new_name='reporting',
        ),
        migrations.RenameModel(
            old_name='Student_upload_assignment',
            new_name='upload_assignment',
        ),
        migrations.RenameModel(
            old_name='Student_upload_projects',
            new_name='upload_projects',
        ),
    ]
