# Generated by Django 4.2.2 on 2023-11-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_admin', '0002_alter_suprt_admin_register_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super_admin_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_email', models.CharField(max_length=500)),
                ('login_password', models.CharField(max_length=200)),
            ],
        ),
    ]
