# Generated by Django 4.2.2 on 2023-11-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_admin', '0004_super_admin_login_login_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super_admin_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=500)),
                ('profile_address', models.CharField(max_length=500)),
                ('profile_gender', models.CharField(max_length=100)),
                ('profile_M_number', models.IntegerField(default=0)),
                ('profile_DOB', models.DateField()),
                ('profile_status', models.CharField(max_length=200)),
            ],
        ),
    ]
