# Generated by Django 4.2.2 on 2023-11-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_admin', '0005_super_admin_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super_admin_add_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=500)),
                ('admin_address', models.CharField(max_length=500)),
                ('admin_DOB', models.DateField()),
                ('admin_exprince', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Super_admin_add_event_activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_A_name', models.CharField(max_length=300)),
                ('E_A_Notice', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Super_admin_add_faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=500)),
                ('faculty_position', models.CharField(max_length=200)),
                ('faculty_address', models.CharField(max_length=500)),
                ('faculty_exprience', models.CharField(max_length=200)),
                ('faculty_subjects', models.CharField(max_length=200)),
                ('faculty_class', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Super_admin_add_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=500)),
                ('student_address', models.TextField()),
                ('student_course', models.CharField(max_length=500)),
                ('student_DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Super_admin_exam_time_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_std', models.CharField(max_length=50)),
                ('exam_date', models.CharField(max_length=200)),
                ('exam_subject', models.CharField(max_length=200)),
                ('exam_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Super_admin_fees_notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=100)),
                ('fees_notice', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Super_admin_time_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_days', models.CharField(max_length=200)),
                ('table_start_time', models.TimeField()),
                ('table_end_time', models.TimeField()),
                ('table_subject', models.TextField()),
                ('table_course', models.CharField(max_length=100)),
            ],
        ),
    ]
