# Generated by Django 4.2.2 on 2023-11-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_admin', '0006_super_admin_add_admin_super_admin_add_event_activite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super_admin_add_parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_name', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('parents_address', models.TextField()),
                ('parents_gender', models.CharField(max_length=20)),
            ],
        ),
    ]
