# Generated by Django 4.2.2 on 2023-11-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_admin', '0007_super_admin_add_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super_admin_time_table',
            name='table_course',
        ),
        migrations.RemoveField(
            model_name='super_admin_time_table',
            name='table_days',
        ),
        migrations.RemoveField(
            model_name='super_admin_time_table',
            name='table_end_time',
        ),
        migrations.RemoveField(
            model_name='super_admin_time_table',
            name='table_start_time',
        ),
        migrations.RemoveField(
            model_name='super_admin_time_table',
            name='table_subject',
        ),
        migrations.AddField(
            model_name='super_admin_time_table',
            name='day1_subject',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='super_admin_time_table',
            name='day2_subject',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='super_admin_time_table',
            name='day3_subject',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='super_admin_time_table',
            name='day4_subject',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='super_admin_time_table',
            name='day5_subject',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='super_admin_time_table',
            name='day6_subject',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='super_admin_time_table',
            name='school_day1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='super_admin_time_table',
            name='school_day2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='super_admin_time_table',
            name='school_day3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='super_admin_time_table',
            name='school_day4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='super_admin_time_table',
            name='school_day5',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='super_admin_time_table',
            name='school_day6',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='super_admin_time_table',
            name='school_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='super_admin_time_table',
            name='school_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='super_admin_time_table',
            name='school_std',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
