# Generated by Django 4.2.2 on 2023-11-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_admin', '0008_remove_super_admin_time_table_table_course_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Super_admin_add_admin',
            new_name='add_admin',
        ),
        migrations.RenameModel(
            old_name='Super_admin_add_event_activite',
            new_name='add_event_activite',
        ),
        migrations.RenameModel(
            old_name='Super_admin_add_faculty',
            new_name='add_faculty',
        ),
        migrations.RenameModel(
            old_name='Super_admin_add_parents',
            new_name='add_parents',
        ),
        migrations.RenameModel(
            old_name='Super_admin_add_student',
            new_name='add_student',
        ),
        migrations.RenameModel(
            old_name='Super_admin_exam_time_table',
            new_name='exam_time_table',
        ),
        migrations.RenameModel(
            old_name='Super_admin_fees_notice',
            new_name='fees_notice',
        ),
        migrations.RenameModel(
            old_name='Super_admin_login',
            new_name='login',
        ),
        migrations.RenameModel(
            old_name='Super_admin_profile',
            new_name='profile',
        ),
        migrations.RenameModel(
            old_name='Suprt_admin_register',
            new_name='register',
        ),
        migrations.RenameModel(
            old_name='Super_admin_time_table',
            new_name='time_table',
        ),
    ]
