# Generated by Django 4.2.2 on 2023-11-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_admin', '0010_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
