# Generated by Django 4.2.2 on 2023-11-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_admin', '0012_remove_user_date_joined_user_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
