# Generated by Django 4.2.2 on 2023-11-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_admin', '0013_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
