# Generated by Django 4.2.2 on 2023-11-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_admin', '0014_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role_choice', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'superadmin'), (2, 'admin'), (3, 'faculty'), (4, 'parents'), (5, 'student')], default=3)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
