# Generated by Django 4.2.2 on 2023-11-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_admin', '0015_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
