# Generated by Django 4.2.2 on 2023-11-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.CharField(max_length=20)),
                ('upload_assignment', models.FilePathField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_attendens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('student_attendens', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_create_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_std', models.CharField(max_length=20)),
                ('result_subjects', models.TextField()),
                ('result_marks', models.TextField()),
                ('result_total_marks', models.CharField(max_length=10)),
                ('returlt_persantag', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_email', models.CharField(max_length=100)),
                ('faculty_password', models.CharField(max_length=50)),
                ('faculty_login_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_address', models.TextField()),
                ('faculty_position', models.CharField(max_length=100)),
                ('faculty_gender', models.CharField(max_length=50)),
                ('faculty_M_Number', models.CharField(max_length=15)),
                ('faculty_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_Projetc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.CharField(max_length=20)),
                ('upload_projects', models.FilePathField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_first_name', models.CharField(max_length=100)),
                ('faculty_last_name', models.CharField(max_length=100)),
                ('faculty_email', models.CharField(max_length=100)),
                ('faculty_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_reprot_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_report', models.TextField()),
            ],
        ),
    ]
