# Generated by Django 4.2.2 on 2023-11-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculty_Assignment',
            new_name='Assignment',
        ),
        migrations.RenameModel(
            old_name='Faculty_attendens',
            new_name='attendens',
        ),
        migrations.RenameModel(
            old_name='Faculty_create_result',
            new_name='create_result',
        ),
        migrations.RenameModel(
            old_name='Faculty_login',
            new_name='login',
        ),
        migrations.RenameModel(
            old_name='Faculty_profile',
            new_name='profile',
        ),
        migrations.RenameModel(
            old_name='Faculty_Projetc',
            new_name='Projetc',
        ),
        migrations.RenameModel(
            old_name='Faculty_register',
            new_name='register',
        ),
        migrations.RenameModel(
            old_name='Faculty_reprot_admin',
            new_name='reprot_admin',
        ),
    ]
