# Generated by Django 4.2.2 on 2023-11-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parents_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_email', models.CharField(max_length=100)),
                ('parents_password', models.CharField(max_length=50)),
                ('parents_login_date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Parents_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_name', models.CharField(max_length=100)),
                ('parents_address', models.TextField()),
                ('parents_email', models.CharField(max_length=100)),
                ('parents_M_Number', models.CharField(max_length=15)),
                ('student_name', models.CharField(max_length=100)),
                ('parents_gender', models.CharField(max_length=20)),
                ('parents_DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Parents_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_first_name', models.CharField(max_length=100)),
                ('parents_last_name', models.CharField(max_length=100)),
                ('parents_email', models.CharField(max_length=100)),
                ('parents_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parents_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_name', models.CharField(max_length=50)),
                ('reporting_subjects', models.CharField(max_length=100)),
                ('reporting_Notice', models.TextField()),
            ],
        ),
    ]
